name: Docker Image CI

on:
  push:
    branches:
      - main
    paths: 
      - 'ubuntu-gcc14/*'
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Buildx setup
      uses: docker/setup-buildx-action@v3.6.1
    - name: Build the Docker image
      run: docker buildx build --tag ubuntu-gcc14:$(date +%s) ubuntu-gcc14
    - name: Log in to the Container registry
      uses: docker/login-action@v3.3.0
      with:
        registry: https://docker.pkg.github.com/
        username: epanteleev
