name: Docker Image CI

on:
  push:
    branches:
      - main
    paths: 
      - 'ubuntu-gcc14/*'
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: docker:latest
      volumes:
        - ${{ github.workspace }}:${{ github.workspace }}
    steps:
    - name: Build the Docker image
      run: |
        cd echo ${{ github.workspace }}
        docker buildx build --output type=docker --tag ghcr.io/epanteleev/ubuntu-gcc14 ubuntu-gcc14
        echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u epanteleev --password-stdin
        docker image ls
        docker push ghcr.io/epanteleev/ubuntu-gcc14
