name: Docker Image CI

on:
  push:
    paths: 
      - "ubuntu-gcc14"
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ubuntu-gcc14 --file Dockerfile --tag my-image-name:$(date +%s)
